
# 默认输出日期的格式
spring:
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 默认输入日期的格式
  mvc:
    format:
      date: yyyy-MM-dd
server:
  port: 8080
  servlet:
    context-path: /